stages:
        - custom

daily-summary:
        stage: custom
        only:
                variables:
                        - $SITUATION == "daily-summary"
        script:
                - ./daily-summary.sh
                - git checkout master
                - git config user.email "bolaoauditer@gitlab.com"
                - git config user.name "Bolao Auditer"
                - git remote add bolao https://gitlab-ci-token:TD9gTsJE5_Vti8D1kBUa@gitlab.com/ibraimedina/bolao2018-audit.git || true
                - git add daily-summary/
                - git commit -am '[daily-summary]'
                - git push bolao master

match-start:
        stage: custom
        only:
                variables:
                        - $SITUATION == "match-start"
        script:
                - ./match-start.sh
                - git checkout master
                - git config user.email "bolaoauditer@gitlab.com"
                - git config user.name "Bolao Auditer"
                - git remote add bolao https://gitlab-ci-token:TD9gTsJE5_Vti8D1kBUa@gitlab.com/ibraimedina/bolao2018-audit.git || true
                - git add match-start/
                - git commit -am '[match-start]'
                - git push bolao master

check-players-count:
        stage: custom
        only:
                variables:
                        - $SITUATION == "check-players-count"
        script:
                - ./check-players-count.sh
