stages:
        - custom

daily-summary:
        stage: custom
        only:
                variables:
                        - $SITUATION == "daily-summary"
        script:
                - ./daily-summary.sh
                - git checkout master
                - git config user.email "bolao2018-audit@gitlab.com"
                - git config user.name "Bolao 2018 audit"
                - git add daily-summary/
                - git commit -am '[daily-summary]'
                - git push origin master

match-start:
        stage: custom
        only:
                variables:
                        - $SITUATION == "match-start"
        script:
                - ./match-start.sh
                - git checkout master
                - git config user.email "bolao2018-audit@gitlab.com"
                - git config user.name "Bolao 2018 audit"
                - git add match-start/
                - git commit -am '[match-start]'
                - git push origin master

check-players-count:
        stage: custom
        only:
                variables:
                        - $SITUATION == "check-players-count"
        script:
                - ./check-players-count.sh
