stages:
        - custom

daily-summary:
        stage: custom
        only:
                variables:
                        - $SITUATION == "daily-summary"
        script:
                - ./daily-summary.sh
                - git checkout master
                - git commit -am '[daily-summary]'

match-start:
        stage: custom
        only:
                variables:
                        - $SITUATION == "match-start"
        script:
                - ./match-start.sh
                - git checkout master
                - git commit -am '[match-start]'

check-players-count:
        stage: custom
        only:
                variables:
                        - $SITUATION == "check-players-count"
        script:
                - ./check-players-count.sh
